[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "fileshimstem"
version = "0.1.5"
description = "A shim between the filesystem and ... the internet. Probably a bad idea."
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"

keywords = [
    "terrible"
]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.78.0"
uvicorn = {extras = ["standard"], version = "^0.17.6"}
GitPython = "^3.1.27"

[tool.poetry.dev-dependencies]
pylint = "^2.14.0"
pytest = "^7.1.2"
black = "^22.3.0"
mypy = "^0.960"
requests = "^2.27.1"
pylint-pydantic = "^0.1.4"


[project.scripts]
fileshimstem = "fileshimstem.__main__:run"

[tool.poetry.scripts]
fileshimstem = "fileshimstem.__main__:run"

[tool.pylint.MASTER]
disable="W0511"
max-line-length=200
extension-pkg-whitelist="pydantic"
load-plugins="pylint_pydantic"