[build-system]
requires = [
    "flit_core >=3.2,<4"
]
build-backend = "flit_core.buildapi"

[project]
authors = [
    {name = "James Hodgkinson", email = "james@terminaloutcomes.com"}
]
classifiers = [
    "License :: OSI Approved :: MIT License"
]
dynamic = [
    "version",
    "description"
]

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "GitPython",
]

keywords = [
    "terrible"
]
name = "fileshimstem"
readme = "README.md"

[project.optional-dependencies]
dev = [
    "pytest",
    "pylint",
    "mypy",
    "flit",
]

[project.urls]
Home = "https://github.com/yaleman/fileshimstem"

[project.scripts]
fileshimstem = "fileshimstem.__main__:run"


[tool.flit.sdist]
exclude = [
    "requirements*.txt",
    ".gitignore",
    ".pylintrc",
    "*.json.example*",
]
